//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clipboarder.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clipboarder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ASPX {
            get {
                object obj = ResourceManager.GetObject("ASPX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] BAT_Mode {
            get {
                object obj = ResourceManager.GetObject("BAT_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Boo {
            get {
                object obj = ResourceManager.GetObject("Boo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Coco_Mode {
            get {
                object obj = ResourceManager.GetObject("Coco_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] CPP_Mode {
            get {
                object obj = ResourceManager.GetObject("CPP_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] CSharp_Mode {
            get {
                object obj = ResourceManager.GetObject("CSharp_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Database {0} is not available.
        ///Exiting now... 的本地化字符串。
        /// </summary>
        internal static string DatabaseNotAvailable {
            get {
                return ResourceManager.GetString("DatabaseNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure of deleting all entries? 的本地化字符串。
        /// </summary>
        internal static string DeleteAllConfirm {
            get {
                return ResourceManager.GetString("DeleteAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap document_save {
            get {
                object obj = ResourceManager.GetObject("document_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_copy {
            get {
                object obj = ResourceManager.GetObject("edit_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Empty Results 的本地化字符串。
        /// </summary>
        internal static string EmptyResults {
            get {
                return ResourceManager.GetString("EmptyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap favorite {
            get {
                object obj = ResourceManager.GetObject("favorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] HTML_Mode {
            get {
                object obj = ResourceManager.GetObject("HTML_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_x_generic {
            get {
                object obj = ResourceManager.GetObject("image_x_generic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Java_Mode {
            get {
                object obj = ResourceManager.GetObject("Java_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] JavaScript_Mode {
            get {
                object obj = ResourceManager.GetObject("JavaScript_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap mail_mark_not_junk {
            get {
                object obj = ResourceManager.GetObject("mail_mark_not_junk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; &gt;
        ///	&lt;xsd:annotation&gt;
        ///		&lt;xsd:documentation&gt;
        ///		This schema defines the syntax for mode definitions in SharpDevelop.
        ///		The schema can be simplified quite a bit but it does the job as is.
        ///		
        ///		
        ///		If you are using this file as a reference it is probably easiest to scroll to
        ///		the botton to find the definition of the root element called SyntaxDefinition and
        ///		then unwind the different type definitions and ref [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ModeXSD {
            get {
                return ResourceManager.GetString("ModeXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Page ({0}) 的本地化字符串。
        /// </summary>
        internal static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Patch_Mode {
            get {
                object obj = ResourceManager.GetObject("Patch_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] PHP_Mode {
            get {
                object obj = ResourceManager.GetObject("PHP_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap process_stop {
            get {
                object obj = ResourceManager.GetObject("process_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Search &amp; Delete 的本地化字符串。
        /// </summary>
        internal static string SearchAndDeleteTitle {
            get {
                return ResourceManager.GetString("SearchAndDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap shadow {
            get {
                object obj = ResourceManager.GetObject("shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 System is busy, try pressing F5 to refresh 的本地化字符串。
        /// </summary>
        internal static string StatusOperationTimedout {
            get {
                return ResourceManager.GetString("StatusOperationTimedout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;SyntaxModes version=&quot;1.0&quot;&gt;
        ///	&lt;Mode file       = &quot;ASPX&quot;
        ///	      name       = &quot;ASP/XHTML&quot;
        ///	      extensions = &quot;.asp;.aspx;.asax;.asmx&quot;/&gt;
        ///	
        ///	&lt;Mode file       = &quot;BAT_Mode&quot;
        ///	      name       = &quot;BAT&quot;
        ///	      extensions = &quot;.bat&quot;/&gt;
        ///	
        ///	&lt;Mode file       = &quot;Boo&quot;
        ///	      name       = &quot;Boo&quot;
        ///	      extensions = &quot;.boo&quot;/&gt;
        ///	
        ///	&lt;Mode file       = &quot;Coco_Mode&quot;
        ///	      name       = &quot;Coco&quot;
        ///	      extensions = &quot;.atg&quot;/&gt;
        ///	
        ///	&lt;Mode file       = &quot;CPP_Mode&quot;
        ///	      name       = &quot;C++.NET&quot;
        ///	      extensions = &quot;.c;.h;.cc;.C;. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SyntaxModes {
            get {
                return ResourceManager.GetString("SyntaxModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon SystrayIcon {
            get {
                object obj = ResourceManager.GetObject("SystrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Tex_Mode {
            get {
                object obj = ResourceManager.GetObject("Tex_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap text_html {
            get {
                object obj = ResourceManager.GetObject("text_html", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap text_x_script {
            get {
                object obj = ResourceManager.GetObject("text_x_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap TextEditorControl {
            get {
                object obj = ResourceManager.GetObject("TextEditorControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap unfavorite {
            get {
                object obj = ResourceManager.GetObject("unfavorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] VBNET_Mode {
            get {
                object obj = ResourceManager.GetObject("VBNET_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] XML_Mode {
            get {
                object obj = ResourceManager.GetObject("XML_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
